name: "format all code"

# run on pull requests to develop
on:
  push:
    branches:
      - master
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      # format the latest commit
      - name: Run clang format
        run: |
          apt install clang-format 
          git fetch origin master:master
          git reset --hard master
          find . -iname *.h -o -iname *.c | xargs clang-format -i -style=file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: stupid-formatting